### ISSUE TITLE
Lending days?

### ISSUE THREAD

**Issue by chriscrutt** [BitBotFactory/poloniexlendingbot#522]
I currently have this in my default.cfg file:

    [BTC]
    minloansize = 0.01
    mindailyrate = 0.018
    maxactiveamount = 100
    maxtolend = 0
    maxpercenttolend = 100
    maxtolendrate = 0
    spreadlend = 1

the other options I put as defaluts are:

    mindailyrate = 0.02
    maxdailyrate = 5
    gapMode = Relative
    gapbottom = 100
    gaptop = 600
    xdaythreshold = 0.2
    xdays = 30
    keepstuckorders = True
    hideCoins = False

I also attached my file.

The problem is, the bot recently just lent at 0.02747%, for a period of 10 days on Bitfinex. This is under my xdaythreshold (0.2) and over my xdays (30). I can only guess because it was trying to accommodate for people not accepting my loan offers and made it for a longer period?

Why is it doing this? How can I make it so it only does 2 days lending and then 30 when it gets passed the xdaythreshold?

Thank you!

here's my default.cfg file:

[default.cfg](https://github.com/BitBotFactory/poloniexlendingbot/files/1316069/default.cfg.txt)

**Comment by rnevet** [comment]
@mahiso can you look into this, could it be that the xdaysspread isn't disabled by commenting  it out?

**Comment by mahiso** [comment]
@rnevet No idea at the moment. xdayspread should be "0" when commented out:

https://github.com/BitBotFactory/poloniexlendingbot/blob/c1a483836794cdf4cb9ace8197b3c9987678622f/modules/Lending.py#L73

and days will only calculated using it when > 0:

https://github.com/BitBotFactory/poloniexlendingbot/blob/c1a483836794cdf4cb9ace8197b3c9987678622f/modules/Lending.py#L168

Will check it, but have to wait until some coins are back from lending.

@chriscrutt I recommended that you revoke your api key and generate a new one, because your key is in submitted config file and public now...

**Comment by chriscrutt** [comment]
shoot ok haha, and it may be something I did, let's wait until the period is over and to what period the next one is.

**Comment by chriscrutt** [comment]
it seems to be working now, thanks!
